services:
  client:
    build:
      args:
        NEXT_PUBLIC_SERVER_URL: https://monopoly.zeblawrence.com/api
    environment:
      NEXT_PUBLIC_SERVER_URL: https://monopoly.zeblawrence.com/api
    ports: [] # nginx proxies, don't expose directly
    expose:
      - '3000'

  server:
    environment:
      CLIENT_ORIGIN: https://monopoly.zeblawrence.com
      NODE_ENV: production
    ports: [] # nginx proxies, don't expose directly
    expose:
      - '3001'
